#!/bin/sh
set -e

sed --in-place "s@%RPC_HOST%@${RPC_HOST:-127.0.0.1}@g" /opt/webui-aria2/configuration.js
sed --in-place "s@%RPC_PORT%@${RPC_PORT:-6800}@g" /opt/webui-aria2/configuration.js
sed --in-place "s@%RPC_SECRET%@${RPC_SECRET:-}@g" /opt/webui-aria2/configuration.js
